#!/bin/bash

declare tmpFile="$(mktemp)";

cleanup() {
	rm -f "$tmpFile";
}

trap cleanup EXIT;

jspacker -b ./ -i "/src/auto.js" -n -e -M '["terser", "-m", "--module", "--compress", "pure_getters,passes=3", "--ecma", "2020"]' -o "$tmpFile";

zopfli --gzip --i1000 -c "$tmpFile" > auto.js.gz;
